version: "1"
services:
  auth-service:
    build: ./auth-service
    ports:
      - 3001:3001
    environment:
      PROVIDER_HOST: provider
  booking-service:
    build: ./booking-service
    ports:
      - 3002:3002
      - 5000:5000
    environment:
      PROVIDER_HOST: provider
  imdb-service:
    build: ./imdb-service
    environment:
      PROVIDER_HOST: provider
  movie-service:
    build: ./movie-service
    ports:
      - 3000:3000
    environment:
      PROVIDER_HOST: provider

